## Instalar a biblioteca NUMPY (no terminal)

pip install numpy

In [60]:
#Importar Biblioteca
import numpy as np

#Cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])

print("-------")

print(mt)

print("-------")

print(type(mt))

In [61]:
#Criar o array com um tipo especifico
#criar o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print (mtfloat)

print("-------")

print(type(mtfloat))

print("-------")

mtint = np.array([1, 2, 3], dtype = np.int32)
print (mtint)

print("-------")

print(type(mtint))

[1. 2. 3.]
-------
<class 'numpy.ndarray'>
-------
[1 2 3]
-------
<class 'numpy.ndarray'>


In [62]:
#Mudar o tipo do array
#Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print (mtnew)

print("-------")

#Quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
-------
[ 1  3 -5  9  4]


In [63]:
#Podemos fazer o inverso também
mt5 = np.array([1, 2, 3, 4])
print (mt5)

print("-------")

mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
-------
[1. 2. 3. 4.]


In [64]:
#Mais de uma dimensão
#Cria uma matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print (mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [65]:
#criar arrays vazios tipificados
#Empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)

print("-------")

#Criar uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)

print("-------")

#com valores igual a um
um = np.ones([5,7])
print(um)

print("-------")

#Criar matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [66]:
#Valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)

print("-------")

#Valores aleatórios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)

print("-------")

#Valores aleatórios 3x4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.88473409 0.51561318 0.22050679 0.66165546 0.45474746]
-------
[-1.68044216 -1.85761866 -0.93217657 -1.99668736 -0.10042957]
-------
[[3.38779293 1.72823236 2.07579445 8.16138135]
 [3.23449962 3.46154686 6.90512917 7.97339234]
 [7.2037644  8.59414782 5.58332212 8.13517288]]


In [67]:
#Outra forma de gerar aleatórios
#Uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

[0.51182162 0.9504637  0.14415961]


In [68]:
#Gerar inteiros
ale6 = gnr.integers(10, size=(3, 4))
print(ale6)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [69]:
#Unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [70]:
#Funções específicas
#Criar a matriz bidimensional k
k = np.array([[17,22,43], [27,25,14],[15,24,32]])

#Mostrar a matriz k
print(k)

print("-------")

#Mostrar um elemento especifico da matriz k
print(k[0][1])

print("-------")

#Mostrar o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
-------
22
-------
(3, 3)


In [71]:
#Funções Matemáticas
#Mostrar o maior valor da matriz k
print(k.max())

print("-------")

#Mostrar o menor valor da matriz k
print(k.min())

print("-------")

#Mostrar a soma dos valores da matriz k
print((k.sum()))

print("-------")

#Mostrar o valor da média dos valores da matriz k
print(k.mean())

print("-------")

#Mostrar o valor do desvio padrāo (standard deviation) dos valores da matiz k
print(k.std())

43
-------
14
-------
219
-------
24.333333333333332
-------
8.615231988880057


In [72]:
#Funções universais, aplicadas a todos os elementos
#Mostrar o valor da raiz quadrada de todos elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

print("-------")

#Mostrar o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
-------
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [73]:
#extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])

#Mostrar o elemento da posição 2
print(m[1])

print("-------")

#Mostrar o array criado a partir da posição 0, dois elementos
print(m[0:2])

print("-------")

#Mostrar o array criado a partir da 2ª posição
#Até todo o restante do array
print(m[1:])

print ("-------")

#Mostrar o array criado a partir da antepenúltima
#Posição até o final
print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [74]:
#Extração de Linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)

print ("-------")

#Primeira Linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)

print ("-------")

#Segunda Linha
l_linha_2 = l[1, :]
print (l_linha_2)

print("-------")

#Terceira Linha
l_linha_3 = l[2, :]
print(l_linha_3)

print ("-------")

#Todas as Linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)

print ("------")

#todas as Linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
------
[5 1 4]


In [75]:
#Adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)

print("-------")
                             
res2 = n*o
print(res2)

print("-------")

P = np.array([[1, 2], [3, 40], [5, 6]])
q = np.array([[2, 1]])
print(P+q)

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[ 3  3]
 [ 5 41]
 [ 7  7]]


In [76]:
#Transposição, rearranja um conjunto de 15 elementos de 0 a 14
#Em 3 Linhas e 5 colunas.
f = np.arange(15).reshape((3, 5))

#Mostrar a matrizes transposta entre Linha e coluna
print(f)

print("-------")

s = f.T
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [77]:
#Outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3, 5))
print(r)

print("-------")

#Rearranjar um conjunto de 15 elementos
#mostrar a matrizes transposta entre Linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [78]:
#Expressões lógicas
#Usando where
#Criando matriz com valores aleatórios positivos e negativas
v = np.random.randn(4, 4)
print(v)

print("-------")

#Criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)

print("-------")

#Criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[-0.28669684  1.25178213 -0.35741336 -1.24895178]
 [-0.59783684  0.34981825 -1.60581235  0.2514662 ]
 [ 0.15506963  1.81607958  1.01576887  1.20986864]
 [-1.94535254  1.18637366 -0.69180733 -0.48060081]]
-------
[[False  True False False]
 [False  True False  True]
 [ True  True  True  True]
 [False  True False False]]
-------
[[-1  1 -1 -1]
 [-1  1 -1  1]
 [ 1  1  1  1]
 [-1  1 -1 -1]]
